// ============================================================
// 파트너 데이터 편집 파일
// ------------------------------------------------------------
// 파트너를 추가/수정하려면 아래 목록에 { ... } 항목을 추가/편집하면 됩니다.
// 필터링이 걸려있지 않을 때는 여기 적힌 순서대로 왼쪽부터 나열됩니다.
//
// 전투원(agents/agents-data.js)과 다른 점:
//   - attribute(속성) 필드가 없습니다. 파트너는 속성 분류가 없어요.
//   - grade(등급)는 5 / 4 / 3 까지 존재합니다.
//   - grade 아이콘 이미지는 agents 폴더의 것을 그대로 재사용합니다
//     (agents/grade_5.png, grade_4.png, grade_3.png / grade_5_tag.png, grade_4_tag.png, grade_3_tag.png).
//
// 각 항목의 항목 설명:
//   id          : 파트너 고유 값 (영문/숫자, 중복 금지)
//   name        : 파트너 이름
//   job         : 직업 하나만 선택 — striker / ranger / vanguard / hunter / controller / psionic
//   grade       : 등급 하나만 선택 — 5 (5성) / 4 (4성) / 3 (3성)
//   illust      : 우측에 크게 보여줄 일러스트 이미지 경로 (partner 폴더에 넣고 파일명 적기)
//   icon        : 하단 목록에 보여줄 작은 아이콘 이미지 경로 (비워두면 illust와 동일한 이미지 사용)
//   tagline     : 이름 아래 한 줄 소개 문구
//   description : 상세 설명 (줄바꿈하고 싶은 곳에서 Enter로 줄을 바꾸면 그대로 반영됩니다)
// ============================================================

window.PARTNER_DATA = [
  {
    id: 'yuni',
    name: '유니',
    job: 'ranger',
    grade: 5,
    illust: 'partner/유니_B.png',
    icon: 'partner/유니_A.webp',
    tagline: '폭스 소대의 브레이크 담당',
    description: '아이언 레인 폭스 소대 소속.\n소대장을 향한 충성심이 대단하며, 그 충섬심을 정론과 잔소리로 표현한다.\n힐데가 무모한 작전을 가져오면 누구보다 먼저 나서서 반대하고\n정론으로 받아 치지만, 작전 수행 중에는 맡은 역할을 완벽하게 해낸다.',
    passive: '전장 포화 교범',
    passive_tooltip: '담당 전투원의 공격력이 16/18/20/22/24% 증가합니다.\n담당 전투원이 뽑을 카드에서 "본능" 속성 공격 카드 생성 시\n그 카드의 추가 공격 피해량이 사용시까지 40/50/60/70/80% 증가합니다.',
    ego: '전방 사격 개시!',
    ego_point: 2,
    ego_tooltip: '피해 250%\n핸드에 담당 전투원의 무작위\n공격 카드 1장 약점 공격 2 부여',
    ego_media: 'partner/유니_D.webp',
  },
  {
    id: 'ruixiang',
    name: '루이샹',
    job: 'ranger',
    grade: 5,
    illust: 'partner/루이샹_B.png',
    icon: 'partner/루이샹_A.webp',
    tagline: '페이의 보호자라고 주장하는 안드로이드 소녀',
    description: '활기차고 매력적인 안드로이드 소녀. 루이샹은 놀라울\n정도로 뛰어난 웅변 능력을 지니고 있으며, 그녀와 대화하는 사람들은\n자연스럽게 마음을 열게 된다. 겉으로는 어린 소녀처럼 보이지만\n내면에 오래된 영혼을 지니고 있다.',
    passive: '좋은 향은 남는 법',
    passive_tooltip: '담당 전투원의 공격력이 16/18/20/22/24% 증가합니다.\n담당 전투원이 뽑을 카드에 공허 속성 공격 카드를 생성 시마다 [은은한 잔향] 1을 획득합니다.\n[은은한 잔향] : 담당 전투원 피해량 +5/6/7/8/10% (최대 5 중첩)',
    ego: '향연',
    ego_point: 3,
    ego_tooltip: '담당 전투원의 공격 카드 드로우 1\n그 카드의 비용이 0 또는 X라면 드로우 2',
    ego_media: 'partner/루이샹_D.webp',
  },
  {
    id: 'priscilla',
    name: '프리실라',
    job: 'striker',
    grade: 5,
    illust: 'partner/프리실라_B.png',
    icon: 'partner/프리실라_A.webp',
    tagline: '테트라 가문의 가주',
    description: '군사 가문인 테트라 가문의 가주가 일찍 사망하면서,\n후계자인 프리실라는 어린 나이에 가주 자리에 올랐다.\n나이가 어려 무시하는 세력들을 제압하기 위해, 프리실라는\n폭군처럼 방해자들을 숙청하며 현재의 자리를 유지하고 있다.',
    passive: '거미의 영역',
    passive_tooltip: '담당 전투원의 공격력, 체력, 피해량이 12/14/16/18/20% 증가합니다.\n담당 전투원이 격파 상태인 대상에게 주는 피해가 +25/32/38/44/50% 됩니다.',
    ego: '테트라의 거미줄',
    ego_point: 2,
    ego_tooltip: '피해 250%\n핸드에 담당 전투원의 무작위\n공격 카드 1장 약점 공격 2 부여',
    ego_media: 'partner/프리실라_D.webp',
  },
  {
    id: 'solia',
    name: '솔리아',
    job: 'ranger',
    grade: 5,
    illust: 'partner/솔리아_B.png',
    icon: 'partner/솔리아_A.webp',
    tagline: '레오스 가문의 선구자',
    description: '방주 체레스 문명의 선구자인 솔리아는 다른 실레이마와 비교해도 지지 않을\n막강한 힘을 지녔다. 강자 특유의 여유와 제멋대로인 성격으로 누구도\n이해할 수 없는 존재로 여겨지고 있지만, 사실은 사람을 이해하는데\n서툰 것뿐. 대부분의 행동은 자신만의 방식으로 선의를 베푸는 것이다.',
    passive: '시공의 비틀림',
    passive_tooltip: '담당 전투원의 공격력이 12/14/16/18/20% 증가합니다.\n담당 전투원이 주는 추가 공격 피해량이 +20/25/30/35/40% 됩니다.',
    ego: '시공간 균열',
    ego_point: 3,
    ego_tooltip: '피해 250%\n표식 1',
    ego_media: 'partner/솔리아_D.webp',
  },
  {
    id: 'eishlen',
    name: '아이슐렌',
    job: 'vanguard',
    grade: 5,
    illust: 'partner/아이슐렌_B.png',
    icon: 'partner/아이슐렌_A.webp',
    tagline: '이노스의 야망',
    description: '병약함과 무력함을 야망과 집념, 비상한 머리로 극복해낸 천재.\n금단의 마도서를 얻어 미지의 존재의 힘을 빌려 쓰게 되었다.\n그 능력과 성격적 결함을 감안하는 한이 있더라도,\n아이슐렌은 명실공히 실레이마의 한 축이다.',
    passive: '마력 파동',
    passive_tooltip: '담당 전투원의 방어력, 체력, 실드 획득량이 12/14/16/18/20% 증가합니다.',
    ego: '이노스의 수호',
    ego_point: 4,
    ego_tooltip: '실드 100%\n턴 종료 시 실드 50% 보존',
    ego_media: 'partner/아이슐렌_D.webp',
  },
  {
    id: 'serithea',
    name: '세리테아',
    job: 'hunter',
    grade: 5,
    illust: 'partner/세리테아_B.png',
    icon: 'partner/세리테아_A.webp',
    tagline: '귀족을 동경하는 아가씨',
    description: '실레이마 특유의 거만함은 있지만 다른 사람들의 눈에\n얄팍한 허세처럼 귀엽게 보이는 정도다. 약간의 애정결핍이 있으며,\n부족한 자존감을 채우기 위해 남들에게 사랑받을 수 있는 컨셉을\n만들어 자신인 척 위장하고 다닌다.',
    passive: '앙상블',
    passive_tooltip: '담당 전투원의 공격력이 12/14/16/18/20% 증가합니다.\n담당 전투원의 공격 카드의 치명확률이 +8/10/12/14/16% 됩니다.',
    ego: '진홍빛 로맨스',
    ego_point: 3,
    ego_tooltip: '피해 250%\n취약 2',
    ego_media: 'partner/세리테아_D.webp',
  },
  {
    id: 'nyx',
    name: '닉스',
    job: 'controller',
    grade: 5,
    illust: 'partner/닉스_B.png',
    icon: 'partner/닉스_A.webp',
    tagline: '에란테 가문의 장녀',
    description: '일찌감치 에란테의 후계자 자리를 차지하여,\n가주에게만 이어져 내려오는 에란테 코어를 일찌감치\n물려받고 후계자 수업 중이다. 현재는 바깥세상들을 직접\n돌아다니면서 여러 가지를 경험하며 배우고 있다.',
    passive: '공명',
    passive_tooltip: '담당 전투원의 방어력, 체력, 치유량이 12/14/16/18/20% 증가합니다.',
    ego: '에란테 허리케인',
    ego_point: 4,
    ego_tooltip: '카드 3장까지 버리기\n버린 수 +1만큼 드로우',
    ego_media: 'partner/닉스_D.webp',
  },
  {
    id: 'anteia',
    name: '안테이아',
    job: 'psionic',
    grade: 5,
    illust: 'partner/안테이아_B.png',
    icon: 'partner/안테이아_A.webp',
    tagline: '로고스 가문의 천재 관측자',
    description: '실레이마 중에서도 유독 셈법에 강한 로고스 가문 소속의 인물.\n차가운 이성과 계산의 가문 내 인물답게, 감정보다\n이성적으로 판단하고 생각하며, 천재이기 때문인지\n평범한 인간은 이해하기 어려운 언행을 하기도 한다.',
    passive: '미래 관측',
    passive_tooltip: '담당 전투원의 방어력, 체력, 치유량이 12/14/16/18/20% 증가합니다.',
    ego: '학술적 조치',
    ego_point: 2,
    ego_tooltip: '모든 적 피해 180%\n취약 1',
    ego_media: 'partner/안테이아_D.webp',
  },
  {
    id: 'lilian',
    name: '릴리안',
    job: 'striker',
    grade: 4,
    illust: 'partner/릴리안_B.png',
    icon: 'partner/릴리안_A.webp',
    tagline: '노력하는 완벽주의자',
    description: '나이트메어호의 요원으로 대인관계를 맺는 것에 서투르다.\n평소 도도하고 가시 돋친 성격이지만 사실 외로움을 타곤 한다.\n기대하고 실망하는 것이 싫어서, 처음부터 기대하지 않는 편.\n상당한 노력파로, 완벽주의 성향을 가지고 있다.',
    passive: '미래 관측',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n담당 전투원의 비용 1 이하인 공격 카드 피해량이 +10/13/15/18/20% 됩니다.\n담당 전투원이 스킬 카드 사용 시 1턴간 공격 카드의 피해량이 +10/13/15/18/20% 됩니다. 최대 3회 중첩됩니다.',
    ego: '심판의 빛',
    ego_point: 3,
    ego_tooltip: '모든 적 피해 100%\n담당 전투원의 비용이 1 이하인 공격 카드 드로우 1',
    ego_media: 'partner/릴리안_D.webp',
  },
  {
    id: 'daisy',
    name: '데이지',
    job: 'ranger',
    grade: 4,
    illust: 'partner/데이지_B.png',
    icon: 'partner/데이지_A.webp',
    tagline: '울프 소대 척후병',
    description: '통신, 정비, 척후 등 다방면으로 활약하는 보조 요원이다.\n작은 몸으로 뭐든지 성실하게 수행하는 모습이\n부대원들의 호감을 사고 있으나, 정작 본인의\n자기 평가는 낮은 편이다.',
    passive: '다우징',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n담당 전투원의 추가 공격 피해량이 10/13/15/18/20% 증가합니다.\n담당 전투원이 턴마다 처음 능력으로 드로우 시 20/25/30/35/40%의 확률로 1턴간 사기 1을 획득합니다.',
    ego: '탐지하겠습니다!',
    ego_point: 2,
    ego_tooltip: '실드 180%\n1턴간 사기 1',
    ego_media: 'partner/데이지_D.webp',
  },
  {
    id: 'rachel',
    name: '레이첼',
    job: 'vanguard',
    grade: 4,
    illust: 'partner/레이첼_B.png',
    icon: 'partner/레이첼_A.webp',
    tagline: '자타공인 대식가',
    description: '본인이 먹을 것을 좋아하며 다른 동료들이 굶고 다니는\n모습을 볼 수 없다는 신념 하에 보급병이 되었다.\n맛있는 건 언제나 환영받기에, 레이첼을 만나는 부대원들은\n대부분 레이첼을 좋아하며 환영한다.',
    passive: '에너지 보충',
    passive_tooltip: '담당 전투원의 스킬 카드 실드 획득량이 10/13/15/18/20% 증가합니다.\n담당 전투원이 실드 획득 시 20/25/30/35/40% 확률로 반격 1을 획득합니다.',
    ego: '햄버거 대령이요~!',
    ego_point: 2,
    ego_tooltip: '실드 100%\n드로우 1',
    ego_media: 'partner/레이첼_D.webp',
  },
  {
    id: 'carroty',
    name: '캐로티',
    job: 'hunter',
    grade: 4,
    illust: 'partner/캐로티_B.png',
    icon: 'partner/캐로티_A.webp',
    tagline: '유전자 변형 매니아',
    description: '유전자 변형을 통해 슈퍼 당근 재배에 성공한 \'헤븐 당근\'의 대표.\n모두에게 가장 맛있는 당근을 맛보게 하기 위해 매일\n고군분투하고 있다. 겁도 많고 눈물도 많아 \'헤븐 당근\'의 작물은\n물 대신 눈물을 쓰고 있다는 소문이 돌고 있다.',
    passive: '슈퍼 당근 파워!',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n담당 전투원이 턴 시작 시 1장의 공격 카드 피해량이 10/13/15/18/20% 증가합니다.\n담당 전투원이 처음으로 카드 생성 시 1턴간 공격 카드의 피해량이 10/13/15/18/20% 증가합니다.',
    ego: '말랑 당근 먹기',
    ego_point: 2,
    ego_tooltip: '1턴간 담당 전투원의 능력으로 생성한 카드의 피해량 20% 증가',
    ego_media: 'partner/캐로티_D.webp',
  },
  {
    id: 'arwen',
    name: '아르웬',
    job: 'controller',
    grade: 4,
    illust: 'partner/아르웬_B.png',
    icon: 'partner/아르웬_A.webp',
    tagline: '별빛의 지성을 지닌 천재',
    description: '현 테라시온 최연소 천재. 최고일지는 몰라도, 최연소임은 분명.\n입버릇처럼 자신이 치천사와 퐁포코의 엄마로서 지켜줘야\n한다고 하는데, 퐁포코와 치천사는 은연중에 아르웬을 지키고 싶어\n하는 것을 보아 서로 상부상조하는 관계인 듯.',
    passive: '별빛의 지성',
    passive_tooltip: '담당 전투원의 체력과 치유량이 8/9/10/11/12% 증가합니다.\n턴 시작 시 행동 예고가 공격상태인 적 수만큼 [퐁포코의 응원]을 획득합니다.\n[퐁포코의 응원] : 받는 피해량 -10/13/15/18/20%\n효과 발동 시 퐁포코의 응원 제거 (최대 3 중첩)',
    ego: '말랑 당근 먹기',
    ego_point: 2,
    ego_tooltip: '1턴간 담당 전투원의 능력으로 생성한 카드의 피해량 20% 증가',
    ego_media: 'partner/아르웬_D.webp',
  },
  {
    id: 'eloise',
    name: '엘로이즈',
    job: 'psionic',
    grade: 4,
    illust: 'partner/엘로이즈_B.png',
    icon: 'partner/엘로이즈_A.webp',
    tagline: '테라시온 기술팀 팀장',
    description: '중앙기술 지원부 소속으로함내 시설, 장치 및 장비 전반의\n정비 검수 등을 맡고 있다. 감정을 잘 표현하지 않기 때문에\n차가운 인상으로 보인다. 함장을 우상처럼 숭배하지만\n업무적인 관계를 유지하려 노력 중이다.',
    passive: '기술 지원',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n담당 전투원의 공격 카드 피해량이 10/13/15/18/20% 증가합니다.\n담당 전투원이 처음으로 카드를 소멸하거나, 상태이상(상태이상에서 변경된 카드 포함) 카드를 획득하면 1턴간 공격 카드의 피해량이 12/15/18/21/24% 증가합니다.',
    ego: '방어 모듈 가동',
    ego_point: 3,
    ego_tooltip: '1턴간 카드 소멸 시 무작위 적 약화 1',
    ego_media: 'partner/엘로이즈_D.webp',
  },
  {
    id: 'douglas',
    name: '더글라스',
    job: 'striker',
    grade: 3,
    illust: 'partner/더글라스_B.png',
    icon: 'partner/더글라스_A.webp',
    tagline: '아쥬르 상단의 경호원',
    description: '거대한 바주카포를 들고서 후방에서 화력을 맡고 있다.\n본래는 캐러밴 방주의 무기상의 아들로, 무기 상회를\n물려받을 수 있었으나 스스로 상인과는 맞지 않는다고\n생각하여 캐러밴 방주의 경호 부대에 지원하게 되었다.',
    passive: '경호',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n전투 시작 시 1턴간 담당 전투원이 주는 피해량이 8/10/12/14/16% 증가합니다.',
    ego: '거대 바주카포',
    ego_point: 2,
    ego_tooltip: '모든 적 피해 120%',
    ego_media: 'partner/더글라스_D.webp',
  },
  {
    id: 'nakia',
    name: '나키아',
    job: 'ranger',
    grade: 3,
    illust: 'partner/나키아_B.png',
    icon: 'partner/나키아_A.webp',
    tagline: '아쥬르의 열혈 군인',
    description: '현재는 용병으로 활동하고 있지만, 여전히 군인으로서의\n정체성을 갖고 활동하고 있다. 정의와, 자신의 신념을\n관철할 수 있다면 어디서든 싸울 수 있다고 말한다.\n실제로도 자신의 신념을 지키기 위해 노력한다.',
    passive: '열혈 군인',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n아군이 적 처치 시 [후방 지원]을 획득합니다.\n[후방 지원] : 공격 카드 피해량 +10/13/15/18/20%',
    ego: '강력한 한 발',
    ego_point: 2,
    ego_tooltip: '피해 200%',
    ego_media: 'partner/나키아_D.webp',
  },
  {
    id: 'raidel',
    name: '라이델',
    job: 'vanguard',
    grade: 3,
    illust: 'partner/라이델_B.png',
    icon: 'partner/라이델_A.webp',
    tagline: '아쥬르 상단의 전략 분석관',
    description: '캐러밴 방주의 경호 부대 소속으로, 본래는 전투원이었다.\n전투원 시절부터 근육 운동을 좋아하여 여러 사람들에게\n근육 훈련을 권하고 있다. 전략 분석관이 된 이후, 머리를 쓰기\n위해서는 운동이 필수라고 주장하지만 진위는 알 수 없다.',
    passive: '전략 분석',
    passive_tooltip: '담당 전투원의 체력이 8/10/12/14/16% 증가합니다.\n담당 전투원이 반격 상태라면 방어 기반 피해량이 8/10/12/14/16% 증가합니다.',
    ego: '약점 분석',
    ego_point: 2,
    ego_tooltip: '실드 100%\n반격 1',
    ego_media: 'partner/라이델_D.webp',
  },
  {
    id: 'yuri',
    name: '유리',
    job: 'hunter',
    grade: 3,
    illust: 'partner/유리_B.png',
    icon: 'partner/유리_A.webp',
    tagline: '블랙 스피카의 악동',
    description: '공학적 재능만은 출중하나, 자신의 능력을 장난이나 함정을\n파는 데에 주로 사용해 실질적인 성과는 많지 않다.\n공학적 윤리관이 없고, 자신의 능력으로\n할 수 있다면 그게 무엇이건 한다.',
    passive: '잔기술',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n처음 셔플 시 담당 전투원이 주는 피해량이 8/10/12/14/16% 증가합니다.',
    ego: '드론 출격!',
    ego_point: 2,
    ego_tooltip: '드로우 2',
    ego_media: 'partner/유리_D.webp',
  },
  {
    id: 'yvonne',
    name: '이본느',
    job: 'controller',
    grade: 3,
    illust: 'partner/이본느_B.png',
    icon: 'partner/이본느_A.webp',
    tagline: '안식수녀회의 신실한 사제',
    description: '기본적으로 상냥하고 신실한 인물로 신의 말씀을 열성적으로\n전도하며 많은 이들을 구원하고자 하는 생각을 가지고 있다.\n열성적으로 다른 사람들에게 오랜 시간 설교를 하는 등,\n항상 전도에 항상 힘쓰고 있다.',
    passive: '축복',
    passive_tooltip: '담당 전투원의 방어력이 8/10/12/14/16% 증가합니다.\n담당 전투원이 공격 카드를 사용하지 않고 턴 종료 시 다음 턴 시작 시 치유 30/38/45/53/60%로 체력을 회복합니다.',
    ego: '축성',
    ego_point: 2,
    ego_tooltip: '치유 100%\n1턴간 불굴 1',
    ego_media: 'partner/이본느_D.webp',
  },
  {
    id: 'zatera',
    name: '사테라',
    job: 'psionic',
    grade: 3,
    illust: 'partner/사테라_B.png',
    icon: 'partner/사테라_A.webp',
    tagline: '아쥬르 상단의 샤먼',
    description: '캐러밴 방주 내에서 작은 사원을 운영하면서\n각종 악귀들을 물리치거나, 점괘나 궁합을 봐주거나,\n여러 상황에 유용한 부적 및 소품들을 판매하고 있다.\n미래를 볼 수는 없지만 운의 흐름을 느낄 수 있다고 한다.',
    passive: '점괘',
    passive_tooltip: '담당 전투원의 공격력이 8/10/12/14/16% 증가합니다.\n체력이 30% 미만인 상태에서 전투 종료 시 체력을 4/5/6/7/8% 회복합니다.',
    ego: '기억의 꽃',
    ego_point: 2,
    ego_tooltip: '실드 200%',
    ego_media: 'partner/사테라_D.webp',
  }
];
