// ============================================================
// 장비 강화(재련 / 신의 망치 / 각인) 데이터 파일
// ------------------------------------------------------------
// window.EQUIP_REFINE  : 재련 목록 — { tooltip }
// window.EQUIP_HAMMER  : 신의 망치 목록 — { grade: 'Unique'|'Legendary'|'Rare', tooltip }
// window.EQUIP_IMPRINT : 장비 각인 목록 — { type: 'light'|'dark', tooltip }
// ============================================================

window.EQUIP_REFINE = [
  { tooltip: '카드 보존, 소멸 시 무작위 적 고정 피해 100% (각각 턴당 2회)' },
  { tooltip: '턴 시작 시와 턴 종료 후 실드를 보유한 상태라면 모든 적 고정 피해 100%' },
  { tooltip: '턴 시작 시 뽑을 카드에 소멸 카드가 있다면 30% 확률로 소멸 카드 드로우 1' },
  { tooltip: '전투 시작 시 자신의 소멸 카드 드로우 1' },
  { tooltip: '자신의 소멸 카드를 아군 능력으로 드로우 시 즉시 발동 (턴당 1회)' },
  { tooltip: '공격 카드 피해량 20% 증가' },
  { tooltip: '실드 획득량 15% 증가, 치유량 15% 증가' },
  { tooltip: '피해를 완전히 막으면 다음 턴 시작 시 1턴간 아군 피해량 10% 증가 (턴당 1회)' },
  { tooltip: '전투 시작 시 보유한 카드가 33장 이상이면 공격 카드 피해량 30% 증가' },
  { tooltip: '전투 시작 시 보유한 카드가 18장 이하이면 공격 카드 피해량 30% 증가' },
  { tooltip: '소멸 카드 피해량 25% 증가' },
  { tooltip: '비용 2 이상인 공격 카드 피해량 25% 증가' },
  { tooltip: '전투 시작 시 저장 1' },
  { tooltip: '취약 상태인 적에게 공격 카드 발동 시 치명확률 +15%' },
  { tooltip: '1턴간 적에게 카드로 피해를 입히지 않았다면 다음 턴 시작 시 1턴간 피해량 50% 증가' },
  { tooltip: '턴 시작 시 핸드의 아군 소멸 카드 수만큼 무작위 적 고정 피해 60%' },
  { tooltip: '반격 시 모든 적 방어 기반 피해 200% (턴당 1회)' },
  { tooltip: '카드로 실드 획득 시 고정 실드 100% (턴당 1회)' },
  { tooltip: '비용 3 이상인 카드 발동 시 행동 포인트 1 (턴당 1회)' },
  { tooltip: '행동 포인트 1 이상 보유한 채로 턴 종료 시 모든 적 취약 1' },
  { tooltip: '비용 1 이하인 공격 카드 피해량 +30%' },
  { tooltip: '추가 공격 피해량 25% 증가' },
  { tooltip: '방어 기반 피해량 +30%' },
  { tooltip: '능력으로 자신의 공격 카드 드로우 시 그 카드 1턴간 피해량 50% 증가' }
];

window.EQUIP_HAMMER = [
  // ---- Unique ----
  { grade: 'Unique', tooltip: '치명피해 + 20 %' },
  { grade: 'Unique', tooltip: '공격력 + 15 %, 최대 체력 + 10 %' },
  { grade: 'Unique', tooltip: '전투 시작 시 면역 2' },
  { grade: 'Unique', tooltip: '실드 획득량 + 40 %' },
  { grade: 'Unique', tooltip: '4 번째 턴 시작 시 모든 적 고정 피해 550 %' },
  { grade: 'Unique', tooltip: '격파 상태인 대상에게 피해량 30 % 증가' },
  { grade: 'Unique', tooltip: '실드 획득 시 고정 실드 100 % (턴당 1 회)' },
  { grade: 'Unique', tooltip: '비용 1 이하인 공격 카드의 피해량 25 % 증가' },
  { grade: 'Unique', tooltip: '턴 시작 시 핸드의 아군 페르소나 카드 수만큼 1턴간 자신의 피해량 20% 증가' },
  { grade: 'Unique', tooltip: '행동 전인 대상에게 피해량 25 % 증가' },
  { grade: 'Unique', tooltip: '받는 피해량 10 % 감소 (턴당 1 회)' },
  { grade: 'Unique', tooltip: '카드 소멸 시 다음 사용하는 카드의 피해량 35 % 증가 (최대 1 회 중첩)' },
  { grade: 'Unique', tooltip: '공격력 + 12 %, 방어력 + 12 %' },
  { grade: 'Unique', tooltip: '비용 0 인 공격 카드의 피해량 40 % 증가' },
  { grade: 'Unique', tooltip: '턴 시작 시 반격 1' },
  { grade: 'Unique', tooltip: '전체 공격의 피해량 25 % 증가' },
  { grade: 'Unique', tooltip: '치유 혹은 회복 시 회복량의 50 %만큼 모든 적 고정 피해' },
  { grade: 'Unique', tooltip: '적 수만큼 피해량 7 % 증가 전체 공격의 피해량 10 % 증가' },
  { grade: 'Unique', tooltip: '적이 혼자라면 피해량 30 % 증가' },
  { grade: 'Unique', tooltip: '실드 획득량 25 % 증가' },
  { grade: 'Unique', tooltip: '아군 실드 획득량 15 % 증가' },
  { grade: 'Unique', tooltip: '능력으로 드로우 시 1 턴간 자신의 공격 카드 피해량 35 % 증가 (턴당 1 회)' },
  { grade: 'Unique', tooltip: '방어력 + 15 %, 실드 20 % 보존' },
  { grade: 'Unique', tooltip: '피해량 + 40 %, 턴 종료 시 30 % 확률로 핸드의 카드 1 장 소멸' },
  { grade: 'Unique', tooltip: '전투 시작 시 3 장까지 버리기, 그 수만큼 드로우' },
  { grade: 'Unique', tooltip: '공격 카드 사용 시 고정 실드 20 % (턴당 10 회)' },
  { grade: 'Unique', tooltip: '턴 종료 시 무작위 적들에게 고정 피해 40 % x 2 ~ 6 , 아군에게 고정 피해 200 % 중 무작위 1 개의 효과 발동' },

  // ---- Legendary ----
  { grade: 'Legendary', tooltip: '턴 시작 시 아군 페르소나 카드가 핸드에 있다면 아군 스트레스 2 감소' },
  { grade: 'Legendary', tooltip: '충격파 상태인 대상에게 피해량 30% 증가' },
  { grade: 'Legendary', tooltip: '피격 시 공격자에게 공명 2(턴당 3회)' },
  { grade: 'Legendary', tooltip: '공격 카드 사용 시 체력감소 1 %, 고정 실드 60 %' },
  { grade: 'Legendary', tooltip: '피해를 받은 다음 턴 시작 시 고정 실드 80 %' },
  { grade: 'Legendary', tooltip: '카드로 드로우 시 1 턴간 피해량 + 20 % (턴당 2 회)' },
  { grade: 'Legendary', tooltip: '치명타 시 치유 10 %' },
  { grade: 'Legendary', tooltip: '턴 시작 시 모든 적 행동 카운트 3 증가' },
  { grade: 'Legendary', tooltip: '고통 상태인 대상에게 피해량 20 % 증가' },
  { grade: 'Legendary', tooltip: '카오스 교단 전투 시 방어력 + 15 %' },
  { grade: 'Legendary', tooltip: '카드를 생성할 때마다 1턴간 피해량 +20% (턴당 2회)' },
  { grade: 'Legendary', tooltip: '3 번째 턴 시작 시 고정 실드 250 %' },
  { grade: 'Legendary', tooltip: '치명피해 + 12 %' },
  { grade: 'Legendary', tooltip: '피격 시 공격자에게 취약, 약화, 손상 중 무작위 1 개 부여 (턴당 3 회)' },
  { grade: 'Legendary', tooltip: '실드 보유하고 턴 시작 시 고정 실드 80 %' },
  { grade: 'Legendary', tooltip: '치명타 시 대상에게 50 % 확률로 고통 1' },
  { grade: 'Legendary', tooltip: '격파 시 대상에게 손상 2' },
  { grade: 'Legendary', tooltip: '공격력 + 15 % 실드 보유 대상에게 피해를 줄 시 대상에게 응징 1' },
  { grade: 'Legendary', tooltip: '기본 공격 카드의 피해량 40 % 증가' },
  { grade: 'Legendary', tooltip: '행동 포인트 10 이상 사용 시 면역 2 (전투당 1 회)' },
  { grade: 'Legendary', tooltip: '강화 카드 사용 시 1 턴간 피해량 + 30 %' },
  { grade: 'Legendary', tooltip: '능력으로 자신의 공격 카드 드로우 시 그 카드 1 턴간 피해량 + 50 %' },
  { grade: 'Legendary', tooltip: '전투 시작 시 회피 1' },
  { grade: 'Legendary', tooltip: '전투 시작 시 피해 감소 1 , 드로우 1' },
  { grade: 'Legendary', tooltip: '행동 포인트 5 이상 사용 시 피해량, 실드 획득량, 치유량 + 25 % (전투당 1 회)' },
  { grade: 'Legendary', tooltip: '턴마다 두 번째 공격 카드부터 피해량 20 % 증가' },
  { grade: 'Legendary', tooltip: '카드 소멸 시 다음 사용하는 카드의 피해량 25 % 증가 (최대 1 회 중첩)' },
  { grade: 'Legendary', tooltip: '엘리트 전투 시작 시 피해량 + 50 %' },
  { grade: 'Legendary', tooltip: '아군이 금기 카드 사용 시 최대 체력의 3 % 회복, 고정 실드 80 %' },
  { grade: 'Legendary', tooltip: '격파 시 고정 실드 60 %' },
  { grade: 'Legendary', tooltip: '상태이상, 저주 카드 드로우 시 1 턴간 피해량 + 12 %' },
  { grade: 'Legendary', tooltip: '상태이상, 저주 카드 드로우 시 1 턴간 피해량 + 15 %' },
  { grade: 'Legendary', tooltip: '핸드의 카드가 4 장 이상일 시 피해량 30 % 증가' },
  { grade: 'Legendary', tooltip: '비용 1 이하인 공격 카드의 피해량 20 % 증가' },
  { grade: 'Legendary', tooltip: '적 수만큼 피해량 6 % 증가' },
  { grade: 'Legendary', tooltip: '능력으로 반격 획득 시 반격 1 추가' },
  { grade: 'Legendary', tooltip: '카드 소멸 시 무작위 적 고정 피해 40 %' },
  { grade: 'Legendary', tooltip: '공격 카드 사용 시 준 피해량의 9 % 만큼 회복 (턴당 1 회)' },
  { grade: 'Legendary', tooltip: '격파 시 대상에게 고정 피해 150 %' },
  { grade: 'Legendary', tooltip: '강화 카드 사용 시 피해 감소 1' },
  { grade: 'Legendary', tooltip: '에고 포인트 3 이하라면 치명타 시 에고 포인트 0.2 획득' },
  { grade: 'Legendary', tooltip: '최대 체력인 상태라면 피해량 + 50 %' },
  { grade: 'Legendary', tooltip: '격파 시 다음 사용하는 공격 카드 1 장의 피해량 + 100 %' },
  { grade: 'Legendary', tooltip: '능력으로 카드를 버릴 시, 모든 적 공명 1 (턴당 3회)' },
  { grade: 'Legendary', tooltip: '행동 예고가 공격인 적이 있을 시 고정 실드 60 % (턴당 1 회)' },
  { grade: 'Legendary', tooltip: '치유 혹은 회복 시 치유량의 35 %만큼 모든 적 고정 피해' },
  { grade: 'Legendary', tooltip: '홀수 턴에 공격력 + 8 %, 방어력 + 12 %' },
  { grade: 'Legendary', tooltip: '짝수 턴에 공격력 + 12 %, 방어력 + 8 %' },
  { grade: 'Legendary', tooltip: '치유 혹은 회복 시 회복량의 50 %만큼 무작위 적 고정 피해' },
  { grade: 'Legendary', tooltip: '단일 공격 카드 사용 시 대상의 행동 카운트 2 증가 (턴당 1회)' },
  { grade: 'Legendary', tooltip: '공격 카드 사용 시 5 % 확률로 타격 1 회 추가' },
  { grade: 'Legendary', tooltip: '치명확률 + 6 %' },
  { grade: 'Legendary', tooltip: '피해량 + 30 % 받는 스트레스 0 으로 변경 (전투당 1 회)' },
  { grade: 'Legendary', tooltip: '치명타 시 고정 실드 10 %' },
  { grade: 'Legendary', tooltip: '아군의 연결 카드 사용 시, 모든 적 행동 카운트 2 증가 (턴당 1회)' },
  { grade: 'Legendary', tooltip: '아군이 능력으로 카드를 3장 버릴 때 마다 무작위 적 취약, 표식 중 무작위 1개 부여 (턴당 5회)' },
  { grade: 'Legendary', tooltip: '능력으로 안식 카드를 버릴 때 마다 고정 실드 80% (턴당 2회)' },
  { grade: 'Legendary', tooltip: '턴 시작 시 고정 실드 40 %' },
  { grade: 'Legendary', tooltip: '턴 종료 시 치유 40 %' },
  { grade: 'Legendary', tooltip: '처치 시 모든 적 고정 피해 200 %' },
  { grade: 'Legendary', tooltip: '피격 시 피해량 10 % 증가 (최대 3 회 중첩)' },
  { grade: 'Legendary', tooltip: '공격 카드 피해량 +40% 공격 카드의 대상 수가 2 이상일 시 대상 수 만큼 피해량 -10% (최대 -30%)' },
  { grade: 'Legendary', tooltip: '최대 체력 + 12 %' },
  { grade: 'Legendary', tooltip: '턴 시작 시 핸드의 상태이상, 저주 카드 수만큼 치유 60 %' },
  { grade: 'Legendary', tooltip: '실드 보유 대상에게 피해를 줄 시 다음 사용하는 공격 카드의 피해량 + 100 %' },
  { grade: 'Legendary', tooltip: '카드 소멸 시 무작위 적에게 응징 1 (턴당 2 회)' },
  { grade: 'Legendary', tooltip: '적 처치 시 공격 카드의 피해량 + 25 % (최대 2 회)' },
  { grade: 'Legendary', tooltip: '피해를 받을 시 공격자에게 표식 1' },
  { grade: 'Legendary', tooltip: '최대 체력의 50 % 이하인 대상에게 피해량 35 % 증가' },
  { grade: 'Legendary', tooltip: '강화 카드 사용 시 1 턴간 피해량 + 30 %' },
  { grade: 'Legendary', tooltip: '전투 시작 시 핸드의 카드 1 장 1 턴간 비용 0 으로 변경' },
  { grade: 'Legendary', tooltip: '공격을 실드로 완벽하게 막으면 모든 적 손상 1 (턴당 1 회)' },
  { grade: 'Legendary', tooltip: '4 번째 턴 시작 시 모든 적 고정 피해 400 %' },
  { grade: 'Legendary', tooltip: '턴 시작 시 최대 체력의 40 % 미만이면 최대 체력의 5 % 회복' },
  { grade: 'Legendary', tooltip: '카드로 취약 부여 시 대상에게 약화 1' },
  { grade: 'Legendary', tooltip: '피해를 받을 시 공격자에게 고통 4' },
  { grade: 'Legendary', tooltip: '턴 시작 시 적 수만큼 고정 실드 25 %' },
  { grade: 'Legendary', tooltip: '복제됨 카드 사용 시 1 턴간 모든 적의 행동 카운트 감소하지 않음 (전투당 1 회)' },
  { grade: 'Legendary', tooltip: '비용이 2 이상인 공격 카드의 피해량 30 % 증가 (턴당 1 회)' },
  { grade: 'Legendary', tooltip: '핸드의 카드가 6 장 이상일 시 피해량 25 % 증가' },
  { grade: 'Legendary', tooltip: '피해량 + 20 %, 실드 획득량 + 20 %' },
  { grade: 'Legendary', tooltip: '니힐럼 전투 시작 시 모든 적 취약 3' },
  { grade: 'Legendary', tooltip: '1 턴간 해로운 효과를 부여했다면 턴 종료 시 고정 실드 80 %' },
  { grade: 'Legendary', tooltip: '능력으로 드로우 시 1 턴간 피해량 20 % 증가 (턴당 2 회)' },

  // ---- Rare ----
  { grade: 'Rare', tooltip: '카오스 교단 전투 시작 시 피해량 + 20 %, 피해 감소 1' },
  { grade: 'Rare', tooltip: '공격 카드 사용 시 준 피해량의 6 % 만큼 회복 (턴당 1 회)' },
  { grade: 'Rare', tooltip: '능력으로 드로우 시 1 턴간 실드 획득량 + 25 % (턴당 2 회)' },
  { grade: 'Rare', tooltip: '능력으로 드로우 시 무작위 적 고정 피해 50 %' },
  { grade: 'Rare', tooltip: '전투 시작 시 회피 1' },
  { grade: 'Rare', tooltip: '전투 종료 시 최대 체력의 5 % 회복' },
  { grade: 'Rare', tooltip: '능력으로 드로우 시 고정 실드 40 %' },
  { grade: 'Rare', tooltip: '턴 종료 시 아군 페르소나 카드가 핸드에 있다면 무작위 적 고정 피해 150%' },
  { grade: 'Rare', tooltip: '턴 종료 시 보존된 카드가 있다면 고정 실드 60 %' },
  { grade: 'Rare', tooltip: '아군이 능력으로 카드를 버릴 시 피해 감소 1 (턴당 1회)' },
  { grade: 'Rare', tooltip: '공격력 10 %, 치명확률 - 5 %' },
  { grade: 'Rare', tooltip: '세크레드 전투 시 피해량 + 25 %, 모든 적 취약 2' },
  { grade: 'Rare', tooltip: '공격 카드 사용 시 대상에게 고통 1 (턴당 1 회) 인베이더 전투라면 고통 2 추가' },
  { grade: 'Rare', tooltip: '능력으로 연결 카드를 버릴 시 1턴간 피해량 20% 증가 (턴당 1회)' },
  { grade: 'Rare', tooltip: '턴 종료 시 핸드의 카드 3 장 이상이라면 고정 실드 140 %' },
  { grade: 'Rare', tooltip: '적들의 행동 카운트 증가 시 1턴간 피해량 +30%(턴당 1회)' },
  { grade: 'Rare', tooltip: '카드로 회복 시 1 턴간 아군 공격력 + 10 % (최대 1 회 중첩)' },
  { grade: 'Rare', tooltip: '처치 시 5 ~ 10 크레딧 획득 (전투당 1 회)' },
  { grade: 'Rare', tooltip: '아군이 금기 카드 사용 시 피해량 + 20 %, 실드 획득량 + 20 % (전투당 2 회)' },
  { grade: 'Rare', tooltip: '피해를 받은 다음 턴 시작 시 고정 실드 60 %' },
  { grade: 'Rare', tooltip: '최대 체력 + 6 % 방어력 + 12 %' },
  { grade: 'Rare', tooltip: '카오스 교단 전투 시 방어력 + 10 %' },
  { grade: 'Rare', tooltip: '추가 공격 시 1턴간 치명확률 2% 증가 (턴당 5회)' },
  { grade: 'Rare', tooltip: '최대 체력인 상태라면 피해량 + 40 %' },
  { grade: 'Rare', tooltip: '턴 시작 시 핸드의 무작위 아군 안식 카드 1장 버리기' },
  { grade: 'Rare', tooltip: '피해를 받은 다음 턴 시작 시 고정 실드 60 %' },
  { grade: 'Rare', tooltip: '카드 소멸 시 피해량 + 25 %, 최대 체력의 5 % 회복 (전투당 1 회)' },
  { grade: 'Rare', tooltip: '카드 소멸 시 모든 적 강인도 피해 1 (전투당 1 회)' },
  { grade: 'Rare', tooltip: '니힐럼 전투 시작 시 모든 적 취약 2' }
];

window.EQUIP_IMPRINT = [
  // ---- 빛 ----
  { type: 'light', tooltip: '턴 시작 시 무작위 적에게 고정 피해 50%' },
  { type: 'light', tooltip: '이번 턴에 행동 카운트가 3이상 감소했다면, 행동 카운트가 가장 낮은 적에게 약화 1' },
  { type: 'light', tooltip: '자신의 신속 카드 피해량 25% 증가' },
  { type: 'light', tooltip: '자신의 카드 발동 시 30% 확률로 모든 적 행동 카운트 1 증가 (턴당 1회)' },
  { type: 'light', tooltip: '턴 시작 시 실드를 보유한 무작위 적에게 고정 피해 100%' },
  { type: 'light', tooltip: '아군이 능력으로 카드를 5장 이상 생성 시 자신의 추가 공격 피해량 +30% (턴당 1회)' },
  { type: 'light', tooltip: '턴 시작 시 행동 카운트가 가장 낮은 대상에게 고정 피해 100%' },
  { type: 'light', tooltip: '턴 시작 시 행동 카운트가 가장 낮은 대상에게 약화 2' },
  { type: 'light', tooltip: '턴 종료 시 보존된 카드가 있다면 고정 실드 50%' },
  { type: 'light', tooltip: '적들의 행동 카운트 증가 시, 1턴간 아군의 공격 카드 피해량 +50% (턴당 1회)' },
  { type: 'light', tooltip: '피격 시 공격자에게 취약, 약화 중 무작위 1개 부여 (턴당 1회)' },
  { type: 'light', tooltip: '아군의 신속 카드 발동 시 다음 사용하는 자신의 공격 카드 피해량 25% 증가 (턴당 1회)' },
  { type: 'light', tooltip: '아군이 격파 시 대상의 행동 카운트 2 증가 (턴당 1회)' },
  { type: 'light', tooltip: '빛의 각인 +1' },
  { type: 'light', tooltip: '어둠의 각인 +1' },
  { type: 'light', tooltip: '턴 시작 시 핸드에 연결 카드가 있다면, 무작위 적 공명 1' },

  // ---- 어둠 ----
  { type: 'dark', tooltip: '아군이 능력으로 카드를 2장 버릴 시 안식 카드 1장 드로우 (전투당 1회)' },
  { type: 'dark', tooltip: '아군이 능력으로 안식 카드를 버렸다면 드로우 1 (턴당 1회)' },
  { type: 'dark', tooltip: '자신의 안식 카드의 피해량 25% 증가' },
  { type: 'dark', tooltip: '자신의 소멸 카드의 피해량 25% 증가' },
  { type: 'dark', tooltip: '무덤의 카드 수가 7장 이상일 시 자신의 공격 카드 피해량 30% 증가' },
  { type: 'dark', tooltip: '자신의 카드가 버려졌다면 다음 직접 사용하는 자신의 공격 카드 피해량 +100% (턴당 1회)' },
  { type: 'dark', tooltip: '턴 시작 시 핸드에 안식 카드가 있다면 무작위 적에게 고정 피해 60%' },
  { type: 'dark', tooltip: '무덤이 15장 이상일 시 자신의 공격 카드 치명피해 +15%' },
  { type: 'dark', tooltip: '턴 종료 시 해로운 효과를 보유한 무작위 적에게 고정 피해 100%' },
  { type: 'dark', tooltip: '추가 공격 시 1턴간 사기 1 (턴당 1회)' },
  { type: 'dark', tooltip: '피격 시 핸드의 무작위 안식 카드 1장 버리기 (턴당 1회)' },
  { type: 'dark', tooltip: '자신의 주도 카드가 버려질 시 발동 (턴당 1회)' },
  { type: 'dark', tooltip: '무덤에 카드가 40장 이상이면 사기 2 (전투당 1회)' },
  { type: 'dark', tooltip: '빛의 각인 +1' },
  { type: 'dark', tooltip: '어둠의 각인 +1' },
  { type: 'dark', tooltip: '능력으로 무덤에서 자신의 카드가 소멸될 시 아군의 공격 카드 피해량 +1% (최대 25%)' }
];
