// ============================================================
// 덱 빌딩 게시판 게시물 파일 (1개 파일 = 게시물 1개)
// 글쓰기 화면에서 작성한 내용이 자동 저장된 파일입니다.
// view/like/comment 숫자는 필요하면 직접 수정해도 됩니다.
// ============================================================

window.DECKBUILDER_POSTS = window.DECKBUILDER_POSTS || [];
window.DECKBUILDER_POSTS.push({
  id: "20260813_51089",
  title: "덱 아무렇게나 만들어봤습니다.",
  content: "제가 좋아하는 전투원들로 아무렇게나 만들어봤습니다. ㅎㅎ",
  agentIds: ["hilde","heidemarie","pei"],
  rows: [
    {
      agentId: "hilde",
      cards: [{"key":"a:퀴버 로딩","name":"퀴버 로딩","cost":1,"type":"skill","grade":"blue","media":"../../cards/힐데/blue1.webp","tooltip":"[ 주도 ]\n뽑을 카드에 \"호밍 애로우\" 3장 생성","egoAttr":"instinct","source":"agent","plusCard":"호밍 애로우","agentId":"hilde","job":null,"fixedAwaken":{"cost":1,"type":"upgrade","tooltip":"|[ 유일 / 개막 ]|\n|턴 시작 시| 뽑을 카드에 \"호밍 애로우\" 3장 생성\n|\"호밍 애로우\"가 턴 드로우 대상이 되지 않음|","plusCard":"호밍 애로우"},"commonAwaken":null,"newAwaken":{"tooltip":"자신의 카드 드로우 1","origIdx":12},"personaSlot1":null,"personaSlot2":null},{"key":"a:플라즈마 레인","name":"플라즈마 레인","cost":1,"type":"attack","grade":"blue","media":"../../cards/힐데/blue2.webp","tooltip":"모든 적 피해 60%, 이온화 2","egoAttr":"instinct","source":"agent","agentId":"hilde","job":null,"fixedAwaken":{"cost":1,"type":"skill","tooltip":"|[ 주도 ]|\n|모든 적| 이온화 |3|\n|드로우 1|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"자신의 카드 드로우 1","origIdx":12},"personaSlot1":null,"personaSlot2":null},{"key":"a:드로우 & 릴리즈","name":"드로우 & 릴리즈","cost":1,"type":"skill","grade":"blue","media":"../../cards/힐데/blue3.webp","tooltip":"자신의 공격 카드 드로우 2\n1턴간 사용 시까지 그 카드 피해량 +50%","egoAttr":"instinct","source":"agent","agentId":"hilde","job":null,"fixedAwaken":{"cost":1,"type":"skill","tooltip":"|[ 주도 ]|\n|드로우| 2\n|다음 3번 자신의 추가 공격 시 모든 적 균열 1|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"자신의 카드 드로우 1","origIdx":12},"personaSlot1":null,"personaSlot2":null},{"key":"a:드로우 & 릴리즈","name":"드로우 & 릴리즈","cost":1,"type":"skill","grade":"blue","media":"../../cards/힐데/blue3.webp","tooltip":"[ 복제됨 ]\n자신의 공격 카드 드로우 2\n1턴간 사용 시까지 그 카드 피해량 +50%","egoAttr":"instinct","source":"agent","agentId":"hilde","job":null,"fixedAwaken":{"cost":1,"type":"skill","tooltip":"|주도| 카드 드로우 2\n1턴간 사용 시까지 그 카드 |비용 1 감소|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"이 카드에 개전 부여","origIdx":13},"personaSlot1":null,"personaSlot2":null,"isDuplicate":true},{"key":"a:빅 게임 레인저","name":"빅 게임 레인저","cost":1,"type":"upgrade","grade":"yellow","media":"../../cards/힐데/yellow.webp","tooltip":"[ 유일 / 주도 ]\n타격 시 일점 조준 2","egoAttr":"instinct","source":"agent","agentId":"hilde","job":null,"fixedAwaken":{"cost":0,"type":"upgrade","tooltip":"|[ 유일 / 개전 ]|\n|드로우 2|\n타격 시 일점 조준 2","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null},{"key":"a:볼텍스 애로우","name":"볼텍스 애로우","cost":1,"type":"attack","grade":"purple","media":"../../cards/힐데/purple.webp","tooltip":"[ 유일 ]\n드로우 3\n모든 적 피해 120%\n이번 턴 드로우한 공격 카드 수만큼 피해량 +60% (최대 8장)","egoAttr":"instinct","source":"agent","agentId":"hilde","job":null,"fixedAwaken":null,"commonAwaken":null,"newAwaken":null,"personaSlot1":null,"personaSlot2":null}],
      partnerId: null,
      equipment: {"weapon":{"name":"혼돈의 지적","refine":{"tooltip":"공격 카드 피해량 20% 증가"},"hammer":{"grade":"Unique","tooltip":"치명피해 + 20 %"},"imprint":null},"armor":{"name":"보강형 전투 강화복","refine":null,"hammer":null,"imprint":null},"accessory":{"name":"양자 포집기","refine":null,"hammer":null,"imprint":null}}
    },
    {
      agentId: "heidemarie",
      cards: [{"key":"a:검광","name":"검광","cost":1,"type":"attack","grade":"gray","media":"../../cards/하이데마리/attack.webp","tooltip":"피해 100%","egoAttr":"passion","source":"agent","agentId":"heidemarie","job":null,"fixedAwaken":null,"commonAwaken":null,"newAwaken":null,"personaSlot1":null,"personaSlot2":null},{"key":"a:검막","name":"검막","cost":1,"type":"skill","grade":"gray","media":"../../cards/하이데마리/skill.webp","tooltip":"실드 100%","egoAttr":"passion","source":"agent","agentId":"heidemarie","job":null,"fixedAwaken":null,"commonAwaken":null,"newAwaken":null,"personaSlot1":null,"personaSlot2":null},{"key":"a:검의 비","name":"검의 비","cost":1,"type":"attack","grade":"blue","media":"../../cards/하이데마리/blue1.webp","tooltip":"피해 80% × 2\n감응 : \"극광검\" 1장 생성","egoAttr":"passion","source":"agent","plusCard":"극광검","agentId":"heidemarie","job":null,"fixedAwaken":null,"commonAwaken":null,"newAwaken":null,"personaSlot1":null,"personaSlot2":null},{"key":"q:꿈의 세계","name":"꿈의 세계","cost":3,"type":"attack","grade":"yellow","gradeColor":null,"media":"../../quiz/꿈의세계.webp","tooltip":"[ 안식 ]\n피해 300%\n버려질 시 뽑을 카드에서;무작위 카드 2장 버리기","egoAttr":"common","source":"common","plusCard":null,"agentId":null,"job":null,"fixedAwaken":null,"commonAwaken":{"tooltip":"드로우 2"},"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null},{"key":"q:꿈의 세계","name":"꿈의 세계","cost":3,"type":"attack","grade":"yellow","gradeColor":null,"media":"../../quiz/꿈의세계.webp","tooltip":"[ 복제됨 / 안식 ]\n피해 300%\n버려질 시 뽑을 카드에서;무작위 카드 2장 버리기","egoAttr":"common","source":"common","plusCard":null,"agentId":null,"job":null,"fixedAwaken":null,"commonAwaken":{"tooltip":"드로우 2"},"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null,"isDuplicate":true},{"key":"q:꿈의 세계","name":"꿈의 세계","cost":3,"type":"attack","grade":"yellow","gradeColor":null,"media":"../../quiz/꿈의세계.webp","tooltip":"[ 복제됨 / 안식 ]\n피해 300%\n버려질 시 뽑을 카드에서;무작위 카드 2장 버리기","egoAttr":"common","source":"common","plusCard":null,"agentId":null,"job":null,"fixedAwaken":null,"commonAwaken":{"tooltip":"드로우 2"},"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null,"isDuplicate":true},{"key":"q:꿈의 세계","name":"꿈의 세계","cost":3,"type":"attack","grade":"yellow","gradeColor":null,"media":"../../quiz/꿈의세계.webp","tooltip":"[ 복제됨 / 안식 ]\n피해 300%\n버려질 시 뽑을 카드에서;무작위 카드 2장 버리기","egoAttr":"common","source":"common","plusCard":null,"agentId":null,"job":null,"fixedAwaken":null,"commonAwaken":{"tooltip":"드로우 2"},"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null,"isDuplicate":true}],
      partnerId: null,
      equipment: {"weapon":null,"armor":null,"accessory":null}
    },
    {
      agentId: "pei",
      cards: [{"key":"a:구마의 형세","name":"구마의 형세","cost":1,"type":"upgrade","grade":"blue","media":"../../cards/페이/blue1.webp","tooltip":"[ 개전 / 유일 ]\n능력으로 드로우 시 강림 1\n뽑을 카드에 \"염무곡\" 8장 생성","egoAttr":"void","source":"agent","plusCard":"염무곡","agentId":"pei","job":null,"fixedAwaken":{"cost":0,"type":"upgrade","tooltip":"[ 개전 / 유일 ]\n능력으로 드로우 시 강림 1\n뽑을 카드에 \"염무곡\" 8장 생성\n|드로우 2|","plusCard":"염무곡"},"commonAwaken":null,"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null},{"key":"a:독무","name":"독무","cost":0,"type":"skill","grade":"blue","media":"../../cards/페이/blue2.webp","tooltip":"드로우 2\n드로우한 카드 중 비용이 1 이상인 카드 모두 버리기","egoAttr":"void","source":"agent","agentId":"pei","job":null,"fixedAwaken":{"cost":0,"type":"skill","tooltip":"드로우 \\1\\\n|비용이 2 이하인 자신의 카드 드로우 시 그 카드 발동하고 드로우 2|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null},{"key":"a:독무","name":"독무","cost":0,"type":"skill","grade":"blue","media":"../../cards/페이/blue2.webp","tooltip":"드로우 2\n드로우한 카드 중 비용이 1 이상인 카드 모두 버리기","egoAttr":"void","source":"agent","agentId":"pei","job":null,"fixedAwaken":{"cost":0,"type":"skill","tooltip":"[ 복제됨 ]\n드로우 \\1\\\n|비용이 2 이하인 자신의 카드 드로우 시 그 카드 발동하고 드로우 2|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null,"isDuplicate":true},{"key":"a:독무","name":"독무","cost":0,"type":"skill","grade":"blue","media":"../../cards/페이/blue2.webp","tooltip":"드로우 2\n드로우한 카드 중 비용이 1 이상인 카드 모두 버리기","egoAttr":"void","source":"agent","agentId":"pei","job":null,"fixedAwaken":{"cost":0,"type":"skill","tooltip":"[ 복제됨 ]\n드로우 \\1\\\n|비용이 2 이하인 자신의 카드 드로우 시 그 카드 발동하고 드로우 2|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"행동 포인트 1 획득","origIdx":8},"personaSlot1":null,"personaSlot2":null,"isDuplicate":true},{"key":"a:밤새 내리는 비","name":"밤새 내리는 비","cost":0,"type":"skill","grade":"blue","media":"../../cards/페이/blue3.webp","tooltip":"염무 1\n연속 : \"염무곡\" 1장 드로우","egoAttr":"void","source":"agent","plusCard":"염무곡","agentId":"pei","job":null,"fixedAwaken":{"cost":0,"type":"skill","tooltip":"염무 1\n연속 : |다음 X를 X+2로 적용|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"자신의 카드 드로우 1","origIdx":12},"personaSlot1":null,"personaSlot2":null},{"key":"a:혼염무","name":"혼염무","cost":"X","type":"attack","grade":"yellow","media":"../../cards/페이/yellow.webp","tooltip":"피해 100% × X+1\n드로우 X","egoAttr":"void","source":"agent","agentId":"pei","job":null,"fixedAwaken":{"cost":"X","type":"skill","tooltip":"드로우 X\n|염무 X × 2|\n|강림 X|","plusCard":null},"commonAwaken":null,"newAwaken":{"tooltip":"드로우 1","origIdx":2},"personaSlot1":null,"personaSlot2":null}],
      partnerId: null,
      equipment: {"weapon":{"name":"혼돈의 지적","refine":null,"hammer":null,"imprint":{"type":"light","tooltip":"턴 시작 시 무작위 적에게 고정 피해 50%"}},"armor":null,"accessory":null}
    }
  ],
  author: "S677524762924",
  view: 0,
  like: 0,
  comment: 0,
  date: "2026-08-13"
});
